# Generated by Django 5.1 on 2024-09-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniedocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='prix',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
