# Generated by Django 5.1 on 2024-09-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniedocs', '0002_cours_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
