# Generated by Django 5.1 on 2024-09-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(blank=True, max_length=255, null=True)),
                ('soustitre', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
