# Generated by Django 5.1 on 2024-09-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexipro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('mot', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Image de profil')),
            ],
        ),
    ]
